version: '3.8'

services:

  php:
    build:
      context: .
      dockerfile: ./docker/php.dockerfile
    env_file:
      - ./environment/php.env
    ports:
      - '8080:80'
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/src/vendor

  mariadb:
    image: mariadb:10.6
    working_dir: /application
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./environment/mariadb.env
    ports:
      - '3306:3306'

  adminer:
    image: adminer:4.8.1
    ports:
      - '8081:8080'
    depends_on:
      - mariadb

  composer:
    build:
      context: .
      dockerfile: ./docker/composer.dockerfile
    volumes:
      - ./backend/src:/home/composer/app

  # TODO
  # mailhog

volumes:
  db_data: {}
